#config_version=6
mode:
    start_events: ball_started
    priority: 100

ball_saves:
    ball_start_ball_save:
        active_time: "+10s"
        hurry_up_time: 2s
        timer_start_events: s_shooter_lane_inactive
        auto_launch: true
        balls_to_save: 1


slide_player:
    mode_base_started: base_slide

light_player:
    ball_save_ball_start_ball_save_timer_start:
        shoot_again: lime
    ball_save_ball_start_ball_save_disabled:
        shoot_again: off
    mode_base_started:
        rads: green
        meds: off
        caps: off
        vlock: off
        vend: off
        big_rad: off
        stims: off
        helmet: ffff00
        vault_boy: off
        slings: yellow

    rads_level1:
        rad1: red
    rads_level2:
        rad2: red
    rads_level3:
        rad3: red
    rads_level4:
        rad4: red
    rads_level5:
        rad5: red
    rads_level6:
        rad6: red
    rads_level7:
        rad7: red
    rads_level8:
        rad8: red
    rads_level9:
        rad9: red
    rads_level10:
        rad10: red
    rads_level0:
        rads: green


variable_player:
    s_rspinner_active:
        score: 100
    s_lspinner_active:
        score: 100
    s_cspinner_active:
        score: 100
    s_left_ramp_active:
        score: 1000
    s_scoop_active:
        score: 1000
    s_lock1_active:
        score: 1000
    s_stand_up1_active:
        score: 500
    s_stand_up2_active:
        score: 500
    s_stand_up3_active:
        score: 500
    s_left_sling_active:
        score: 250
    s_right_sling_active:
        score: 250
    s_l_stand_active:
        score: 500

shots:
    rad_spin:
        switch: s_rspinner
    med_spin:
        switch: s_lspinner
    left_ramp:
        switch: s_left_ramp
    center_ramp:
        switch: s_center_ramp
    right_ramp:
        switch: s_right_ramp
    stand_up1:
        switch: s_stand_up1
    stand_up2:
        switch: s_stand_up2
    stand_up3:
        switch: s_stand_up3
    right_sling:
        switch: s_right_sling
    left_sling:
        switch: s_left_sling
    lock1:
        switch: s_lock1
    lock2:
        switch: s_lock2
    lock3:
        switch: s_lock3
    gun_spin:
        switch: s_cspinner
    l_stand:
        switch: s_l_stand
sound_player:
    rad_spin_hit:
        geiger:
            action: play
            track: sfx
            volume: 1
    med_spin_hit:
        water:
            action: play
            track: sfx
            volume: 1
    left_ramp_hit:
        left_ramp:
            action: play
            track: sfx
            volume: 1
    right_ramp_hit:
        right_ramp:
            action: play
            track: sfx
            volume: 1
    center_ramp_hit:
        objective:
            action: play
            track: sfx
            volume: 1
    stand_up1_hit:
        caps:
            action: play
            track: sfx
            volume: 1
    stand_up2_hit:
        caps:
            action: play
            track: sfx
            volume: 1
    stand_up3_hit:
        caps:
            action: play
            track: sfx
            volume: 1
    right_sling_hit:
        blaster:
            action: play
            track: sfx
            volume: 1
    left_sling_hit:
        blaster:
            action: play
            track: sfx
            volume: 1
    lock1_hit:
        vault_door:
            action: play
            track: sfx
            volume: 1
    lock2_hit:
        vault_door:
            action: play
            track: sfx
            volume: 1
    lock3_hit:
        vault_door:
            action: play
            track: sfx
            volume: 1
    gun_spin_hit:
        gat:
            action: play
            track: sfx
            volume: 1
    l_stand_hit:
        bark:
            action: play
            track: sfx
            volume: 1
    mode_base_started:
        base_start:
            action: play
    mode_base_stopped:
        base_end:
            action: play



counters:
    rad_spin_counter:
        count_events: s_rspinner_active
        starting_count: 0
        count_interval: 1
        count_complete_value: 10
        persist_state: true
        reset_on_complete: true
        disable_on_complete: false

    med_spin_counter:
        count_events: s_lspinner_active
        starting_count: 0
        count_interval: 1
        count_complete_value: 15
        persist_state: true
        reset_on_complete: true
        disable_on_complete: false

    gun_spin_counter:
        count_events: s_cspinner_active
        starting_count: 0
        count_interval: 1
        count_complete_value: 15
        persist_state: true
        reset_on_complete: true
        disable_on_complete: false

multiballs:
    vault_multiball:
        ball_count: 3
        ball_count_type: total
        shoot_again: 10s
        start_events: multiball_lock_v_lock_full
#    release_all_locked_balls:
#        ball_count: current_player.lock_mb6_locked_balls
#        ball_count_type: add
#        shoot_again: 20s
#        start_events: multiball_lock_v_lock_full
#        ball_locks: bd_lock
#        replace_balls_in_play: true
#        balls_to_replace: 2


multiball_locks:
    v_lock:
        balls_to_lock: 3
        lock_devices: bd_lock
        locked_ball_counting_strategy: no_virtual
        enable_events: mode_base_started
#        disable_events: multiball_lock_v_lock_full
#        replace_balls_in_play: true
#        balls_to_replace: 2
state_machines:
    rad_meter_status:
        persist_state: true #so this will hold state across balls
        starting_state: rads0
        states:
            rads0:
                label: Start state
                show_when_active:
                    show: rad_level0_show
                    show_tokens: None
            rads1:
                show_when_active:
                    show: rad_level1_show
                    show_tokens: None
            rads2:
                show_when_active:
                    show: rad_level2_show
                    show_tokens: None
            rads3:
                show_when_active:
                    show: rad_level3_show
                    show_tokens: None
            rads4:
                show_when_active:
                    show: rad_level4_show
                    show_tokens: None
            rads5:
                show_when_active:
                    show: rad_level5_show
                    show_tokens: None
            rads6:
                show_when_active:
                    show: rad_level6_show
                    show_tokens: None
            rads7:
                show_when_active:
                    show: rad_level7_show
                    show_tokens: None
            rads8:
                show_when_active:
                    show: rad_level8_show
                    show_tokens: None
            rads9:
                show_when_active:
                    show: rad_level9_show
                    show_tokens: None
            rads10:
                show_when_active:
                    show: rad_level10_show
                    show_tokens: None
                #etc
        transitions:
            - source: rads0
              target: rads1
              events: logicblock_rad_spin_sequence_complete
            - source: rads1
              target: rads2
              events: logicblock_rad_spin_sequence_complete
            - source: rads2
              target: rads3
              events: logicblock_rad_spin_sequence_complete
            - source: rads3
              target: rads4
              events: logicblock_rad_spin_sequence_complete
            - source: rads4
              target: rads5
              events: logicblock_rad_spin_sequence_complete
            - source: rads5
              target: rads6
              events: logicblock_rad_spin_sequence_complete
            - source: rads6
              target: rads7
              events: logicblock_rad_spin_sequence_complete
            - source: rads7
              target: rads8
              events: logicblock_rad_spin_sequence_complete
            - source: rads8
              target: rads9
              events: logicblock_rad_spin_sequence_complete
            - source: rads9
              target: rads10
              events: logicblock_rad_spin_sequence_complete
            - source: rads10
              target: rads0
              events: reset_rad_meter
    med_meter_status:
        persist_state: true #so this will hold state across balls
        starting_state: med0
        states:
            med0:
                label: Start state
                show_when_active:
                    show: med_level0_show
                    show_tokens: None
            med1:
                show_when_active:
                    show: med_level1_show
                    show_tokens: None
            med2:
                show_when_active:
                    show: med_level2_show
                    show_tokens: None
            med3:
                show_when_active:
                    show: med_level3_show
                    show_tokens: None
            med4:
                show_when_active:
                    show: med_level4_show
                    show_tokens: None
            med5:
                show_when_active:
                    show: med_level5_show
                    show_tokens: None
        transitions:
            - source: med0
              target: med1
              events: logicblock_med_spin_sequence_complete
            - source: med1
              target: med2
              events: logicblock_med_spin_sequence_complete
            - source: med2
              target: med3
              events: logicblock_med_spin_sequence_complete
            - source: med3
              target: med4
              events: logicblock_med_spin_sequence_complete
            - source: med4
              target: med5
              events: logicblock_med_spin_sequence_complete
            - source: med5
              target: med0
              events: reset_med_meter

#using show_when_active like this means it will automatically set the lights
#to match the state machine when a new ball starts, without requiring any
#additional logic or event flags

sequences:
    rad_spin_sequence:
        reset_on_complete: true
        disable_on_complete: false
        events:  #counts 5 hits of the rad_spin shot (spinner rotatations)/completion
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
            - rad_spin_hit
    med_spin_sequence:
        reset_on_complete: true
        disable_on_complete: false
        events:
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
            - med_spin_hit
shows:
#you can just list these shows out here since they're so simple.
    rad_level0_show:
        - time: "+100ms"
          lights:
              rads: green
    rad_level1_show:
        - time: "+100ms"
          lights:
              rads1: red
    rad_level2_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
    rad_level3_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
    rad_level4_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
    rad_level5_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
    rad_level6_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
              rads6: red
    rad_level7_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
              rads6: red
              rads7: red
    rad_level8_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
              rads6: red
              rads7: red
              rads8: red
    rad_level9_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
              rads6: red
              rads7: red
              rads8: red
              rads9: red
    rad_level10_show:
        - time: "+100ms"
          lights:
              rads1: red
              rads2: red
              rads3: red
              rads4: red
              rads5: red
              rads6: red
              rads7: red
              rads8: red
              rads9: red
              rads10: red
              big_rad: red
    rads_level0_show:
        - time: "+100ms"
          lights:
              rads: green

    med_level0_show:
        - time: "+100ms"
          lights:
              meds: off
    med_level1_show:
        - time: "+100ms"
          lights:
              med1: purple
    med_level2_show:
        - time: "+100ms"
          lights:
              med1: purple
              med2: purple
    med_level3_show:
        - time: "+100ms"
          lights:
              med1: purple
              med2: purple
              med3: purple
    med_level4_show:
        - time: "+100ms"
          lights:
              med1: purple
              med2: purple
              med3: purple
              med4: purple
    med_level5_show:
        - time: "+100ms"
          lights:
              meds: off
              stim_right: red
              stim_left: red
    helmet_flash:
        - time: +10ms
          lights:
              helmet:
                  color: red
                  fade: 20ms
        - time: +40ms
          lights:
              helmet:
                  color: ffff00
                  fade: 20ms
    vault_boy_flash:
        - time: +10ms
          lights:
              vault_boy:
                  color: 00D5FF
                  fade: 250ms
    left_sling_flash:
        - duration: +100ms
          lights:
              left_sling:
                  color: FF5500
                  fade: 100ms
    right_sling_flash:
        - duration: +100ms
          lights:
              right_sling:
                  color: FF5500
                  fade: 100ms


show_player:
    rad_spin_hit:
        helmet_flash:
            action: play
            loops: 0
    center_ramp_hit:
        vault_boy_flash:
            action: play
            loops: 0
    left_sling_hit:
        left_sling_flash:
            action: play
            loops: 0
    right_sling_hit:
        right_sling_flash:
            action: play
            loops: 0

    #etc...
