#config_version=6

config:
    - common.yaml

virtual_platform_start_active_switches:
    - s_trough1
    - s_trough2
    - s_trough3

hardware:
    platform: smart_virtual

kivy_config:
    graphics:
        fullscreen: false
        resizable: true
        borderless: 0
        width: 800
        height: 450
        show_cursor: true
        position: auto
