#config_version=6

hardware:
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      3208:
        model: FP-I/O-3208
        order: 1
      "0804":
        model: FP-I/O-0804
        order: 2
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
      playfield:
        model: FP-EXP-0081
    port: /dev/ttyACM1
    baud: 921600
    debug: false
